// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoaofayagbbhenktvchh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYW9mYXlhZ2JiaGVua3R2Y2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDgwNTcsImV4cCI6MjA3OTcyNDA1N30.lXlopcal0g1-wAQ8eUcx7TDcjnU6JhFqlP-WFPYmzJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
