// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vauztcebvsjhirgoivfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdXp0Y2VidnNqaGlyZ29pdmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTE1NTQsImV4cCI6MjA2NDEyNzU1NH0.EULQtCFcyOnFOteBgaNg2GXbcCgjJPr97rkhqrIYUJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);